
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
      tier: app
  template:
    metadata:
      labels:
        app: api-gateway
        tier: app
    spec:
      containers:
      - image: eu.gcr.io/training-193616/kristof-ms-api-gateway:v1
        imagePullPolicy: IfNotPresent
        name: api-gateway
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "15m"
        ports:
        - containerPort: 3000
          protocol: TCP
    