
apiVersion: v1
kind: Service
metadata:
  name: info
  namespace: default
  labels:
    app: info
spec:
  selector:
    app: info
    tier: app
  ports:
  - port: 80
    targetPort: 1338
  type:
    ClusterIP
  