
apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: default
  labels:
    app: users
spec:
  selector:
    app: users
    tier: app
  ports:
  - port: 80
    targetPort: 1337
  type:
    ClusterIP
  