version: '3'
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      USERS_SERVICE_HOST: users
      USERS_SERVICE_PORT: 1337
      INFO_SERVICE_HOST: info
      INFO_SERVICE_PORT: 1338
    ports:
     - "3000:3000"
  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
     - "1337"
  info:
    build:
      context: ./info
      dockerfile: Dockerfile
    ports:
     - "1338"